Homework3
yapijs/home-exercises pull request #3
Opened 2022-09-20 06:53 UTC by yapijs

Finished arrays, classes and objects

2022-10-21 14:40 UTC, NilsKula requested changes

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/arrays/practice/Exercise1.java
> +        for (int num : myArray1) {
šo izvelc uz atsevišku metodi, savadāk 4 identiski for loops

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/arrays/practice/Hangman.java
> +    public static String enterCharacter() {
private

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/arrays/practice/TicTacToe.java
> +        //Checking the rows
no komentāriem noteikti izvairies, daudz labāks risinājums izveidot palīgmetodi ar nosaukumu `checkRowWinner()`

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/arrays/practice/TicTacToe.java
> +    public static boolean isGameEnded() {
private

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise13/AccountTest.java
> +        if (from != null && to != null) {
varētu pielikt ka kaut ko izprintē, ja kāds ir null, bet laba validācija

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise2/Car.java
> +        return calculateConsumption() > 15;
konstante

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise3/FuelGauge.java
> +        if (fuelAmountLeft < 70) {
konstante

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise3/Odometer.java
> +    FuelGauge fuelGauge = new FuelGauge(5);
šeit jau negribēsi veidot jaunu fuel gauge

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise3/Odometer.java
> +    public void fillGasTank(int litres) {
un ši metode noteikti būtu iekš fuelGauge
savadāk caur odometer pildīt degvielu neizkalusās īsti labi :smile:

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise4/Movie.java
> +    String title;
private

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise7/Dog.java
> +        return mother.getName().equals(otherDog.mother.getName());
šķiet ka tikai ar šo rindiņu vajadzētu pietikt :thinking: 
vai nu ir ir tā pati māte savadāk false jebkurā citā gadijumā

2022-10-21 14:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise9/Point.java
> +    int x;
private

2022-10-22 15:59 UTC, yapijs commented on Java-excersises/src/io/codelex/arrays/practice/Hangman.java
> +    public static String enterCharacter() {
izlaboju ne tikai šo vienu metodi, bet arī visas pārējās, jo laikam nav jēgas viņas atstāt publiskas :)

2022-10-22 17:05 UTC, yapijs commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise7/Dog.java
> +        return mother.getName().equals(otherDog.mother.getName());
ja otherDog vai otherDog.mother ir null, nevar izsaukt getName methodi un dabū nullPointerexception.
Bet salīdzina ar sevi, tad gan tiešām nevajag

2022-10-27 13:40 UTC, NilsKula commented on Java-excersises/src/io/codelex/arrays/practice/Hangman.java
> +    public static String enterCharacter() {
yes, tā biju arī domājis :+1:

2022-10-27 13:43 UTC, NilsKula commented on Java-excersises/src/io/codelex/classesandobjects/practice/exercise7/Dog.java
> +        return mother.getName().equals(otherDog.mother.getName());
jā, null check ir labi, so daļu biju domājis, its not wrong, just feels unnecessary :smile: 
```
if (this == otherDog) {
     return true;
}

2022-10-27 13:43 UTC, NilsKula approved these changes

2022-10-27 19:43 UTC, merged